Vagrant.configure(2) do |config|
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.define "ADDBWEB19CODE01" do |vm_config|
        vm_config.vm.provider :azure do |azure, override|
            override.vm.provision :shell, path: "../winrm.ps1"
            override.vm.provision :shell, path: "../PackageManagementProviderResource.ps1"
            override.vm.provision :shell, path: "../basepsmodules.ps1"
            override.vm.provision :shell, path: "../adpsmodules.ps1"
            override.vm.provision :shell, path: "../sqlpsmodules.ps1"
            override.vm.provision :shell, path: "../sppsmodules.ps1"
            override.vm.provision :shell, path: "../adbin.ps1"
            override.vm.provision :shell, path: "../sql2016media.ps1"
            override.vm.provision :shell, path: "../sql2016bin.ps1"
            override.vm.provision :shell, path: "../sql2016mediaclean.ps1", env: {"SPDEVOPSSTARTER_NODSCTEST" => "TRUE"}

            override.vm.provision :shell, path: "../spdomain.ps1", env: {"SPDEVOPSSTARTER_NODSCTEST" => "TRUE"}
            override.vm.provision "reload"
            override.vm.provision :shell, path: "../spdomain.ps1"
            override.vm.provision :shell, path: "../spdomaincustomizations.ps1"

            override.vm.provision :shell, path: "../sp2019media.ps1"
            override.vm.provision :shell, path: "../sp2019mediaclean.ps1", env: {"SPDEVOPSSTARTER_NODSCTEST" => "TRUE"}
            azure.tenant_id = ENV['ARM_TENANT_ID']
            azure.client_id = ENV['ARM_CLIENT_ID']
            azure.client_secret = ENV['ARM_CLIENT_SECRET']
            azure.subscription_id = ENV['ARM_SUBSCRIPTION_ID']
            azure.vm_image_urn = 'MicrosoftWindowsServer:WindowsServer:2016-Datacenter:latest'
            azure.instance_ready_timeout = 3600
            azure.vm_name = 'addbweb19code01'
            azure.location = 'WestUS2'
            azure.vm_size = 'Standard_DS2_v2'
            azure.admin_username = "vagrant"
            azure.vm_password = "Fractalsol365"
            azure.dns_name = (0...15).map { (97 + rand(26)).chr }.join
            override.vm.guest = :windows
            override.vm.box = "azure"
            override.winrm.transport = :ssl
            override.winrm.port = 5986
            override.winrm.ssl_peer_verification = false # must be false if using a self signed cert
        end
        vm_config.vm.boot_timeout = 1800
    end
end